/**
 * GeneratedTeamsList component
 *
 * This component renders the generated teams along with action buttons.
 */

/**
 * Import dependencies
 */

// UI Components
import { Button } from "@/components/ui/button";

// Types
import { GeneratedTeamsListProps } from "@/app/types/entityTypes";

// Components
import GeneratedTable from "@/app/components/generated-teams-list/GeneratedTable";

/**
 * GeneratedTeamsList Component
 *
 * @param {GeneratedTeamsListProps} props - Component props containing `generatedTeams`
 * @returns - Rendered component displaying teams and action buttons
 */
export default function GeneratedTeamsList({
  generatedTeams,
}: GeneratedTeamsListProps) {
  /**
   * Render the GeneratedTeamsList component
   */
  return (
    <section
      aria-labelledby="generated-teams-list-title"
      className="rounded-xl border border-zinc-200 bg-white text-zinc-950 shadow dark:border-zinc-800 dark:bg-zinc-950 dark:text-zinc-50"
    >
      {/* Header Section */}
      <header className="flex flex-col gap-4 p-4 sm:p-6">
        <div className="flex justify-center items-center">
          <h3
            id="generated-teams-list-title"
            className="font-semibold leading-none tracking-tight text-xl"
          >
            Generated Teams
          </h3>
        </div>
        {/* Display generation timestamp */}
        <p className="text-sm sm:text-base text-zinc-500 dark:text-zinc-400 text-center">
          Teams Generated by NoCliques - {new Date().toLocaleString()}
        </p>
      </header>

      {/* Render Generated Teams Table */}
      <GeneratedTable generatedTeams={generatedTeams} />
    </section>
  );
}
