import * as React from "react";

import { Button } from "@/components/ui/button";

export function GeneratedTeamsList() {
  return (
    <section
      aria-labelledby="generated-teams-list-title"
      className="rounded-xl border border-zinc-200 bg-white text-zinc-950 shadow dark:border-zinc-800 dark:bg-zinc-950 dark:text-zinc-50"
    >
      <header className="flex flex-col gap-3 p-6">
        <div className="flex flex-row items-center">
          <div className="flex flex-row gap-2 items-center">
            <h3
              id="generated-teams-list-title"
              className="font-semibold leading-none tracking-tight"
            >
              Generated Teams
            </h3>
          </div>
        </div>
        <p className="text-sm text-zinc-500 dark:text-zinc-400">
          Teams generated by NoCliques - 99/99/9999 99:99
        </p>
      </header>
      <div className="grid sm:grid-cols-2 gap-6 p-6 pt-0">
        <section
          aria-labelledby="generated-team-name-1"
          className=" rounded-xl border border-zinc-200 bg-white text-zinc-950 shadow dark:border-zinc-800 dark:bg-zinc-950 dark:text-zinc-50"
        >
          <div className="p-6">
            <h3
              id="generated-team-name-1"
              className="font-semibold leading-none tracking-tight truncate"
            >
              Team 1{" "}
              <span className="font-light text-zinc-500 dark:text-zinc-400">
                (4 players)
              </span>
            </h3>
          </div>
          <ul className="flex flex-col p-6 pt-0">
            <li className="truncate">
              <strong>Goalkeeper:</strong> Generated Player
            </li>
            <li className="truncate">
              <strong>Defender:</strong> Generated Player
            </li>
            <li className="truncate">
              <strong>Midfielder:</strong> Generated Player
            </li>
            <li className="truncate">
              <strong>Forward:</strong> Generated Player
            </li>
          </ul>
        </section>
        <section
          aria-labelledby="generated-team-name-2"
          className=" rounded-xl border border-zinc-200 bg-white text-zinc-950 shadow dark:border-zinc-800 dark:bg-zinc-950 dark:text-zinc-50"
        >
          <div className="p-6">
            <h3
              id="generated-team-name-1"
              className="font-semibold leading-none tracking-tight truncate"
            >
              Team 2{" "}
              <span className="font-light text-zinc-500 dark:text-zinc-400">
                (4 players)
              </span>
            </h3>
          </div>
          <ul className="flex flex-col p-6 pt-0">
            <li className="truncate">
              <strong>Goalkeeper:</strong> Generated Player
            </li>
            <li className="truncate">
              <strong>Defender:</strong> Generated Player
            </li>
            <li className="truncate">
              <strong>Midfielder:</strong> Generated Player
            </li>
            <li className="truncate">
              <strong>Forward:</strong> Generated Player
            </li>
          </ul>
        </section>
        <section
          aria-labelledby="generated-team-name-3"
          className="rounded-xl border border-zinc-200 bg-white text-zinc-950 shadow dark:border-zinc-800 dark:bg-zinc-950 dark:text-zinc-50"
        >
          <div className="p-6">
            <h3
              id="generated-team-name-1"
              className="font-semibold leading-none tracking-tight truncate"
            >
              Team 3{" "}
              <span className="font-light text-zinc-500 dark:text-zinc-400">
                (4 players)
              </span>
            </h3>
          </div>
          <ul className="flex flex-col p-6 pt-0">
            <li className="truncate">
              <strong>Goalkeeper:</strong> Generated Player
            </li>
            <li className="truncate">
              <strong>Defender:</strong> Generated Player
            </li>
            <li className="truncate">
              <strong>Midfielder:</strong> Generated Player
            </li>
            <li className="truncate">
              <strong>Forward:</strong> Generated Player
            </li>
          </ul>
        </section>
      </div>
      <footer className="flex flex-row justify-end gap-1 items-center p-6 pt-0">
        <Button variant="default" aria-label="Copy" type="button">
          Copy
        </Button>
        <Button variant="default" aria-label="Print" type="button">
          Print
        </Button>
        <Button variant="default" aria-label="Share" type="button">
          Share
        </Button>
        <Button variant="default" aria-label="Download" type="button">
          Download
        </Button>
      </footer>
    </section>
  );
}
