"use client";

/**
 * TeamGenerator Component
 *
 * This component manages player and team inputs, generates balanced teams, and
 * displays the results. It also provides actions for resetting data and generating teams.
 */

/**
 * Import dependencies
 */

// React Hooks
import { useState, useRef } from "react";

// Capture DOM as image
import html2canvas from "html2canvas";

// UI Components
import { Button } from "@/components/ui/button";
import { useToast } from "@/hooks/use-toast";

// Utility Functions
import { initializeEntities } from "@/app/utils/entityUtils";
import {
  generateBalancedTeams,
  formatTeamsForCopy,
} from "@/app/utils/teamGeneratorUtils";

// Types
import { Player, Team, GeneratedTeams } from "@/app/types/entityTypes";

// Components
import GeneratedTeamsList from "@/app/components/generated-teams-list/GeneratedTeamsList";
import EntitiesList from "@/app/components/entities-list/EntitiesList";

/**
 * TeamGenerator component
 */
export default function TeamGenerator() {
  /**
   * State for players and teams
   * Initialize players and teams with default values
   * Players and teams are stored as arrays of Player and Team objects
   * The initializeEntities function is used to create default entities
   */
  const [players, setPlayers] = useState<Player[]>(
    initializeEntities("Players")
  );
  const [teams, setTeams] = useState<Team[]>(initializeEntities("Teams"));

  // Control visibility of generated teams section
  const [isGenerated, setIsGenerated] = useState(false);

  // State to store randomized teams
  const [generatedTeams, setGeneratedTeams] = useState<GeneratedTeams>({});

  // State to store the timestamp of when the teams were generated
  const [generatedAt, setGeneratedAt] = useState<Date | null>(null);

  // Toast notification
  const { toast } = useToast();

  // Ref to the DOM element that will be captured as image
  const resultRef = useRef<HTMLDivElement>(null);

  /**
   * Edit teams and players
   */
  function handleEdit(): void {
    setIsGenerated(false);
    document
      .getElementById("team-generator-title")
      ?.scrollIntoView({ behavior: "smooth" });
  }

  /**
   * Generate teams based on player and team inputs
   * The function uses the generateBalancedTeams function to create balanced teams
   */
  function handleGenerateTeams(): void {
    // Check if players and teams are empty
    if (players.length === 0 || teams.length === 0) {
      toast({
        description: "Please add players and teams before generating.",
      });
      return;
    }
    setGeneratedTeams(generateBalancedTeams(players, teams));
    setGeneratedAt(new Date()); // Stores the date at the time of generation
    setIsGenerated(true);
    document
      .getElementById("team-generator-title")
      ?.scrollIntoView({ behavior: "smooth" });
  }

  /**
   * Copies formatted team data to clipboard
   */
  async function handleCopy(): Promise<void> {
    const formatted = formatTeamsForCopy(generatedTeams, generatedAt);
    try {
      await navigator.clipboard.writeText(formatted);
      toast({
        description: "Generated Teams Copied!",
      });
    } catch (err) {
      alert("Failed to copy. Please try again.");
    }
  }

  /**
   * Downloads an image of the generated team list
   */
  async function handleDownload(): Promise<void> {
    if (!resultRef.current) return;

    const canvas = await html2canvas(resultRef.current);
    const dataUrl = canvas.toDataURL("image/png");

    const link = document.createElement("a");
    link.href = dataUrl;
    link.download = `Teams generated by NoCliques on ${
      generatedAt ? generatedAt.toLocaleString() : "unknown date"
    }.png`;
    link.click();
  }

  /**
   * Shares the generated team image using Web Share API (e.g., WhatsApp)
   */
  async function handleShare(): Promise<void> {
    if (!navigator.canShare || !resultRef.current) {
      alert("Sharing not supported on this device or browser.");
      return;
    }

    const canvas = await html2canvas(resultRef.current);
    canvas.toBlob(async (blob) => {
      if (!blob) return;

      const file = new File([blob], "Teams generated by NoCliques.png", {
        type: "image/png",
      });

      try {
        await navigator.share({
          title: "Generated Teams",
          text: "Check out these balanced teams from NoCliques!",
          files: [file],
        });
      } catch (err) {
        alert("Sharing failed or was canceled.");
      }
    });
  }

  /**
   * Render the TeamGenerator component
   */
  return (
    <section
      id="team-generator-title"
      aria-labelledby="team-generator-title"
      className="bg-white text-zinc-950 dark:bg-zinc-950 dark:text-zinc-50 w-full max-w-5xl mx-auto text-center sm:text-left"
    >
      {/* Header */}
      <header className="flex flex-col space-y-3 p-6 sm:p-8">
        <h2
          id="team-generator-title"
          className="text-4xl font-bold text-center"
        >
          NoCliques
        </h2>
        <p className="text-center max-w-prose mx-auto">
          NoCliques is a team generator app designed to create fair and balanced
          teams avoiding the famous "cliques".
        </p>
      </header>
      <section id="main-section">
        {/* Input Section */}
        {!isGenerated && (
          <section
            aria-labelledby="input-section"
            className="md:flex md:gap-6 p-4 sm:p-6 sm:pt-0 pt-0 space-y-4 sm:space-y-6 md:space-y-0"
          >
            {/* Player Input */}
            <div className="min-w-[280px] w-full md:w-2/3">
              <EntitiesList // Component for player input
                entityType="Players" // Type of entity
                entities={players} // List of entities
                setEntities={setPlayers} // Function to update entities
              />
            </div>

            {/* Team Input */}
            <div className="min-w-[280px] w-full md:w-1/3">
              <EntitiesList // Component for team input
                entityType="Teams" // Type of entity
                entities={teams} // List of entities
                setEntities={setTeams} // Function to update entities
              />
            </div>
          </section>
        )}

        {/* Output Section */}
        {isGenerated && (
          <section
            aria-labelledby="output-section"
            className="p-4 sm:p-6 pt-0 sm:pt-0"
          >
            <div className="min-w-[280px] w-full" ref={resultRef}>
              <GeneratedTeamsList
                generatedTeams={generatedTeams}
                generatedAt={generatedAt}
              />
            </div>
          </section>
        )}
      </section>

      {/* Footer section with action buttons */}
      <footer
        className={`flex flex-col sm:flex-row ${
          isGenerated ? `sm:justify-between` : `sm:justify-center`
        } gap-4 p-4 sm:p-6 pt-0 sm:pt-0`}
      >
        {isGenerated && (
          <div className="flex justify-center gap-4 items-center">
            <Button
              variant="secondary"
              aria-label="Download Generated Teams"
              type="button"
              onClick={handleDownload}
            >
              Download
            </Button>

            <Button
              variant="secondary"
              aria-label="Copy Generated Teams"
              type="button"
              onClick={handleCopy}
            >
              Copy
            </Button>

            <Button
              variant="secondary"
              aria-label="Share Generated Teams"
              type="button"
              onClick={handleShare}
            >
              Share
            </Button>
          </div>
        )}

        <div className="flex justify-center gap-4 items-center">
          {/* Edit Button */}
          {isGenerated && (
            <Button
              className="p-6 text-base sm:text-lg"
              aria-label="Edit Players and Teams"
              type="button"
              variant="outline"
              onClick={handleEdit}
            >
              Edit
            </Button>
          )}

          {/* Generate teams button */}
          <Button
            className="p-6 text-base sm:text-lg"
            aria-label="Generate Teams"
            type="button"
            variant="default"
            onClick={handleGenerateTeams}
          >
            {isGenerated ? "Generate New Teams" : "Generate Teams"}
          </Button>
        </div>
      </footer>
    </section>
  );
}
